# Generated by Django 2.2.6 on 2019-11-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191101_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
    ]
