# Generated by Django 2.2.7 on 2019-11-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191114_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
