# Generated by Django 2.2.6 on 2019-10-31 19:34

from django.db import migrations, models
import django.db.models.deletion
import seeker.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=49)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=6, validators=[seeker.validators.pin_code_validator])),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir ', 'Jammu and Kashmir '), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('National Capital Territory of Delhi', 'National Capital Territory of Delhi'), ('Puducherry', 'Puducherry')], max_length=255)),
                ('educational_qualification', models.CharField(choices=[('BELOW 5th Class', 'BELOW 5th Class'), ('Class 5th to 9th', 'Class 5th to 9th'), ('10th pass', '10th pass'), ('12th pass', '12th pass'), ('ITI', 'ITI'), ('Polytechnic', 'Polytechnic'), ('Diploma', 'Diploma'), ('Graduate (B.Sc., B.A., B.Com.)', 'Graduate (B.Sc., B.A., B.Com.)'), ('Other Graduate (Any Stream)', 'Other Graduate (Any Stream)'), ('B.Tech. (Any Stream)', 'B.Tech. (Any Stream)'), ('M.Tech. (Any Stream)', 'M.Tech. (Any Stream)'), ('Post graduate (Any stream)', 'Post graduate (Any stream)'), ('MBA/PGDM (Any Stream)', 'MBA/PGDM (Any Stream)')], max_length=255)),
                ('experience', models.IntegerField(choices=[(0, '0 to 6 months'), (1, '6 months to 1 year'), (2, '1 year to 2 year'), (3, '2 year to 3 year'), (4, '3 year to 4 year'), (5, 'Four year to 5 year'), (6, 'Above 5')])),
                ('aadhar', models.CharField(max_length=12)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.JobTitle')),
            ],
        ),
    ]
