# Generated by Django 2.2.7 on 2020-05-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        ('core', '0003_jobapplication_comment'),
        ('partner', '0001_initial'),
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('embed', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('account', models.ManyToManyField(blank=True, to='core.Account')),
                ('job', models.ManyToManyField(blank=True, to='core.Job')),
                ('job_title', models.ManyToManyField(blank=True, to='core.JobTitle')),
                ('organisation', models.ManyToManyField(blank=True, to='employer.Organisation')),
                ('partner', models.ManyToManyField(blank=True, to='partner.Partner')),
            ],
        ),
    ]
