# Generated by Django 2.2.7 on 2020-05-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeker', '0002_seekerdocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerdocuments',
            name='account',
        ),
        migrations.AddField(
            model_name='seekerdocuments',
            name='seeker',
            field=models.ManyToManyField(blank=True, to='seeker.Seeker'),
        ),
    ]
